version: "3.8"

services:
  nft-game-server-prod:
    container_name: nft-game-server-prod
    build:
      context: ./
      dockerfile: Dockerfile
      target: production-stage
    env_file: ./.env
  
  nft-game-database-prod:
    container_name: nft-game-database-prod
    image: mysql
    env_file: ./.env
